### ISSUE TITLE
Component Documentation in README is missing sample output

### ISSUE THREAD

**Issue by zubairov** [elasticio/sugarcrm-component#15]
Would be great to have sample output from the action and trigger for that component

**Comment by jhorbulyk** [comment]
The input and output JSON would depend on how the SugarCRM instance is
configured.  Furthermore, what would be the use case of documenting sample
data in a README file when they can more easily and more accurately browse
that data during flow construction?

**Comment by zubairov** [comment]
True, however samples could give a quick answer to the question how resulsts are looking like? Apart from that when creating a new object, what will I get back?

**Comment by jhorbulyk** [comment]
The problem is that the data can be very verbose.  If I create samples with
very verbose data in this document, then I don't think this document will
clearly communicate information to the reader.  If I abridge the data
sample, then readers may incorrectly assume that we are limitied in the
types of data that we can manipulate.

When creating a new object, you will get back the created object.  I can
add that to the documentation.
